baseurl = "https://tyagdit.github.io/"
title = "Tyagraj Desigar's site"
theme = "hugo-theme-console"
languageCode = "en-us"
publishDir = "docs"

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = false
  # This is what appears in the prompt header before the path
  host = "tyagdit@web:/"

  [[params.navlinks]]
  name = "posts/"
  url = "posts/"

  [[params.social]]
      name = "github"
      weight = 1
      url = "https://github.com/tyagdit"
  [[params.social]]
      name = "telegram"
      weight = 2
      url = "https://t.me/altiboi"
  [[params.social]]
      name = "matrix"
      weight = 3
      url = "https://matrix.to/#/@tyagdit:matrix.org"
  [[params.social]]
      name = "tyagdit<small>[at]</small>gmail<small>[dot]</small>com"
      weight = 4
