baseurl = "https://tyagdit.github.io"
title = "Tyagraj Desigar's site"
theme = "hugo-theme-console"
languageCode = "en-us"
publishDir = "docs"

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = false
  # This is what appears in the prompt header before the path
  host = "tyagdit@web:/"

  [[params.navlinks]]
  name = "about/"
  url = "about/"

  [[params.navlinks]]
  name = "posts/"
  url = "posts/"

#   [[params.social]]
#       name = "Github"
#       icon = "fab fa-github"
#       weight = 1
#       url = "https://github.com/johndoe/"
#   [[params.social]]
#       name = "Gitlab"
#       icon = "fab fa-gitlab"
#       weight = 2
#       url = "https://gitlab.com/johndoe/"
#   [[params.social]]
#       name = "Twitter"
#       icon = "fab fa-twitter"
#       weight = 3
#       url = "https://twitter.com/johndoe/"
